### ISSUE TITLE
Duplicate Affinity * Recipes, also these don't pick up version 2

### ISSUE THREAD

**Issue by peterkelm** [autopkg/faumac-recipes#10]
Hi,

I just saw in an autopkg search today that you are offering recipes for Affinity {Designer|Photo|Publisher} products too. It is good practice to avoid duplicates, so we might want to "standardize" on one and retire the other.

FYI: My recipes have a slightly longer history than yours and also support Affinity 2.x product versions already... 

Best regards,

Peter

**Comment by doschupp** [comment]
Hi Peter, 

Actually, this is not a bad idea. However, in your repository are only `download´ and `munki` recipes. Furthermore also without licensing possibility. To consider the recipes, this should be implemented.

We created new recipes for the v2 version (with licensing), but currently only in our internal repo.

**Comment by peterkelm** [comment]
Hi doschupp,

I believe the best approach would be that we integrate our download recipes so that there's just one that can be referenced from both our .munki and your .pkg recipes.

For clarity, I've just added a BSD 3-clause license to our recipe repo, which should eliminate licensing concerns.

BTW: I like the way your use of the app's sparkle feed… but is there a reason why you use your s3 eu-west ones over the more generic ones from the app:

Designer v1: <string>http://go.seriflabs.com/affinity-update-mac-retail-designer</string>
Designer v2: <string>https://go.seriflabs.com/affinity-update-mac-retail-designer2</string>

**Comment by faumac** [comment]
Hi @peterkelm,

We have uploaded the Affinity v2 versions of us. Feel free to adapt them or customize the download parent recipe. Feel free to create a MR for this. 

The sparkle feed URLs are only a redirect.﻿﻿ We adjusted the sparkle URL. However, have set the v2 statically. The reason for this are changes to the licensing proc. - The AffinityDefaults file has been renamed. 
﻿
