### ISSUE TITLE
update is out of date

### ISSUE THREAD

**Issue by mstevens-gc** [autopkg/faumac-recipes#8]
Any chance this can get updated to pull the latest PDF Expert? The latest is 3.0.18 and the recipe downloads 2.5.21.

**Comment by mstevens-gc** [comment]
Very bizarre but the version I had installed says 3.0.16 and it updated to 3.0.18 today in the app but the one that downloads from the site is the one that downloads in this recipe, 2.5.21. I know I downloaded it from Readdle so II'm not so where the other version came from.

**Comment by doschupp** [comment]
Also the AppCast URL in both versions (2 and 3) are the same one https://downloads.pdfexpert.com/release/appcast.xml. That's why he doesn't offer an update within version 2.

I'll keep an eye on it.
